import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import type { AppState, AppThunk } from '../../store'
import { CandidateHuntingState } from './interface'

const initialState: CandidateHuntingState = {
    resumeContent: '',
    JDContent: '',
    ChatQAList: [],
}
export const candidateHuntingSlice = createSlice({
    name: 'candidateHuntingState',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        updateResumeContent: (state, action: PayloadAction<{ resumeContent: string }>) => {
            // state.resumeContent = action.payload.resumeContent
            return {
                ...state,
                resumeContent: action.payload.resumeContent,
            }
        },
        updateJDContent: (state, action: PayloadAction<{ JDContent: string }>) => {
            return {
                ...state,
                resumeContent: action.payload.JDContent,
            }
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: builder => {},
})

export const { updateResumeContent, updateJDContent } = candidateHuntingSlice.actions

export const getCandidateHuntingState = (state: AppState) => state.candidateHunting

export default candidateHuntingSlice.reducer
